name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6.9 (Ubuntu 18.04)
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.9
    - name: Install Tesseract
      run: |
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -u -y ppa:alex-p/tesseract-ocr
        sudo apt-get install -y tesseract-ocr libtesseract-dev tesseract-ocr-eng
    - name: Cache Tesseract traineddata
      uses: actions/cache@v1
      id: cache-tesseract-traineddata
      with:
        path: /usr/share/tesseract-ocr/4.00/tessdata/eng.traineddata
        key: ${{ runner.os }}-tesseract-traineddata
    - name: Download Tesseract trained data
      if: steps.cache-tesseract-traineddata.outputs.cache-hit != 'true'
      run: |
        sudo curl -L -o /usr/share/tesseract-ocr/4.00/tessdata/eng.traineddata https://github.com/tesseract-ocr/tessdata_best/blob/master/eng.traineddata?raw=true
    - name: Cache pip's http cache
      uses: actions/cache@v1
      id: cache-pip
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest pytest-xdist
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest test.py -n auto
